<?php
$title = '批量图片缩放';
$desc = '一次把多张图片调整为统一尺寸并打包下载，适合电商素材、网站配图和汇报图片；图片只在浏览器中处理。';
include '_header.php';
?>
            <style>
            .batch-drop{display:flex;min-height:128px;align-items:center;justify-content:center;padding:20px;border:2px dashed #cbd5e1;border-radius:12px;background:rgba(248,250,252,.7);text-align:center;cursor:pointer}.batch-drop.dragging{border-color:#6366f1;background:rgba(99,102,241,.08)}.batch-drop strong{display:block;margin-bottom:7px;color:#334155}.batch-drop small{color:#64748b}.batch-options{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:16px}.batch-options label{display:block}.batch-options input,.batch-options select{width:100%;margin-top:7px}.batch-summary{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.batch-summary span{padding:5px 9px;border-radius:999px;background:#eef2ff;color:#4338ca;font-size:13px}.batch-status{min-height:22px;margin:12px 0 0;color:#64748b}.batch-status.error{color:#b91c1c}.batch-status.success{color:#047857}.batch-progress{width:100%;margin-top:10px}.batch-results{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.batch-card{min-width:0;overflow:hidden;border:1px solid #dbe3ef;border-radius:11px;background:rgba(255,255,255,.72)}.batch-card img{display:block;width:100%;height:132px;object-fit:contain;background:#f1f5f9}.batch-card .body{padding:9px 10px}.batch-card strong,.batch-card small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.batch-card strong{font-size:13px;color:#334155}.batch-card small{margin-top:5px;color:#64748b;font-size:12px}.batch-card.error{padding:12px;color:#b91c1c;font-size:13px}.batch-empty{grid-column:1/-1;padding:32px;text-align:center;border:1px dashed #cbd5e1;border-radius:11px;color:#64748b}.batch-actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:17px}.quality-wrap input{padding:0}.privacy-note{margin:14px 0 0;color:#475569;font-size:13px}html.theme-dark .batch-drop,html.theme-dark .batch-card{background:rgba(30,41,59,.72);border-color:#475569}html.theme-dark .batch-drop strong,html.theme-dark .batch-card strong{color:#e2e8f0}html.theme-dark .batch-card img{background:#0f172a}html.theme-dark .batch-summary span{background:#312e81;color:#c7d2fe}@media(max-width:820px){.batch-options{grid-template-columns:repeat(2,minmax(0,1fr))}.batch-results{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:560px){.batch-options,.batch-results{grid-template-columns:1fr}.batch-card img{height:175px}}
            </style>
            <div class="tool-panel">
                <label class="batch-drop" id="dropZone" for="files"><span><strong>点击选择或拖放多张图片</strong><small>支持 JPG、PNG、WebP；最多 50 张，总大小不超过 200 MB</small></span></label>
                <input id="files" type="file" accept="image/jpeg,image/png,image/webp" multiple hidden>
                <div class="batch-options">
                    <div><label for="targetWidth">目标宽度（px）</label><input id="targetWidth" type="number" min="1" max="12000" value="1280" inputmode="numeric"></div>
                    <div><label for="targetHeight">目标高度（px）</label><input id="targetHeight" type="number" min="1" max="12000" value="720" inputmode="numeric"></div>
                    <div><label for="fitMode">缩放方式</label><select id="fitMode"><option value="contain">完整显示（留白）</option><option value="cover">裁切填满（不变形）</option><option value="stretch">拉伸填满</option></select></div>
                    <div><label for="background">留白颜色</label><input id="background" type="color" value="#ffffff"></div>
                    <div><label for="format">导出格式</label><select id="format"><option value="image/jpeg">JPG</option><option value="image/webp" selected>WebP</option><option value="image/png">PNG</option></select></div>
                    <div class="quality-wrap"><label for="quality">质量 <span id="qualityValue">85%</span></label><input id="quality" type="range" min="50" max="100" value="85"><small id="qualityHint">适用于 JPG / WebP</small></div>
                    <div><label for="suffix">文件名后缀</label><input id="suffix" maxlength="40" value="_resized" placeholder="例如：_web"></div>
                </div>
                <div class="batch-summary" id="summary"></div><progress class="batch-progress" id="progress" max="100" value="0" hidden></progress><p class="batch-status" id="status" role="status">请先选择图片。</p>
                <div class="batch-actions"><button class="btn" id="process" type="button" disabled>开始批量处理</button><button class="btn success" id="download" type="button" disabled>打包下载 ZIP</button><button class="btn secondary" id="clear" type="button" disabled>移除全部图片</button></div>
                <p class="privacy-note">🔒 图片只在浏览器中处理，不会上传服务器。批量处理会移除原图片的 EXIF 信息（如拍摄位置）。</p>
            </div>
            <div class="tool-panel"><h3>处理结果</h3><div class="batch-results" id="results"><div class="batch-empty">处理完成后会在这里显示图片预览。</div></div></div>
            <script src="../static/vendor/jszip.min.js"></script>
            <script>
            (()=>{
                'use strict';
                const MAX_FILES=50,MAX_FILE_BYTES=40*1024*1024,MAX_TOTAL_BYTES=200*1024*1024,MAX_SOURCE_PIXELS=50000000,MAX_OUTPUT_PIXELS=30000000,MAX_OUTPUT_BYTES=250*1024*1024,MAX_SIDE=12000;
                const allowedTypes=new Set(['image/jpeg','image/png','image/webp']),extensionByType={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};
                const $=id=>document.getElementById(id);let selectedFiles=[],results=[],processing=false;
                const readable=bytes=>bytes>=1048576?(bytes/1048576).toFixed(2)+' MB':bytes>=1024?(bytes/1024).toFixed(1)+' KB':bytes+' B';
                function setStatus(text,type=''){$('status').textContent=text;$('status').className='batch-status '+type;}
                function releaseResults(){results.forEach(result=>{if(result.url)URL.revokeObjectURL(result.url);});results=[];renderResults();$('download').disabled=true;}
                function renderSummary(){const total=selectedFiles.reduce((sum,file)=>sum+file.size,0),box=$('summary');box.replaceChildren();if(selectedFiles.length){[['图片',selectedFiles.length],['原文件',readable(total)]].forEach(([label,value])=>{const item=document.createElement('span');item.textContent=label+'：'+value;box.appendChild(item);});}$('process').disabled=!selectedFiles.length||processing;$('clear').disabled=!selectedFiles.length||processing;}
                function renderResults(errors=[]){const box=$('results');box.replaceChildren();if(!results.length&&!errors.length){box.append(Object.assign(document.createElement('div'),{className:'batch-empty',textContent:'处理完成后会在这里显示图片预览。'}));return;}results.forEach(result=>{const card=document.createElement('article'),image=new Image(),body=document.createElement('div'),name=document.createElement('strong'),meta=document.createElement('small');card.className='batch-card';image.src=result.url;image.alt=result.name;image.loading='lazy';body.className='body';name.textContent=result.name;meta.textContent=result.width+' × '+result.height+' px · '+readable(result.blob.size);body.append(name,meta);card.append(image,body);box.appendChild(card);});errors.forEach(error=>{const card=document.createElement('div');card.className='batch-card error';card.textContent=error;box.appendChild(card);});}
                function resetFiles(fileList){const incoming=[...fileList];if(!incoming.length)return;const invalid=incoming.find(file=>!allowedTypes.has(file.type)||file.size>MAX_FILE_BYTES);const total=incoming.reduce((sum,file)=>sum+file.size,0);if(incoming.length>MAX_FILES||total>MAX_TOTAL_BYTES){setStatus('最多选择 50 张图片，总大小不能超过 200 MB。','error');return;}if(invalid){setStatus('仅支持单张不超过 40 MB 的 JPG、PNG、WebP 图片。','error');return;}selectedFiles=incoming;releaseResults();renderSummary();setStatus('已选择 '+incoming.length+' 张图片，可以开始处理。','success');}
                function outputName(file,type,used){const raw=file.name.replace(/\.[^.]+$/,''),base=raw.replace(/[<>:"/\\|?*\u0000-\u001f]/g,'_').replace(/[. ]+$/g,'').trim().slice(0,110)||'image',suffix=$('suffix').value.replace(/[<>:"/\\|?*\u0000-\u001f]/g,'_').slice(0,40),ext=extensionByType[type];let name=base+suffix+'.'+ext,index=2;while(used.has(name.toLocaleLowerCase())){name=base+suffix+'_'+index+'.'+ext;index++;}used.add(name.toLocaleLowerCase());return name;}
                async function decode(file){if('createImageBitmap'in window){try{const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});return {image:bitmap,width:bitmap.width,height:bitmap.height,release:()=>bitmap.close()};}catch(e){}}const url=URL.createObjectURL(file);try{const image=await new Promise((resolve,reject)=>{const item=new Image();item.onload=()=>resolve(item);item.onerror=()=>reject(new Error('无法读取图片'));item.src=url;});return {image,width:image.naturalWidth,height:image.naturalHeight,release:()=>URL.revokeObjectURL(url)};}catch(error){URL.revokeObjectURL(url);throw error;}}
                const canvasBlob=(canvas,type,quality)=>new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('浏览器无法生成此格式的图片')),type,type==='image/png'?undefined:quality));
                function targetRect(sourceWidth,sourceHeight,targetWidth,targetHeight,mode){if(mode==='stretch')return {x:0,y:0,width:targetWidth,height:targetHeight};const scale=mode==='cover'?Math.max(targetWidth/sourceWidth,targetHeight/sourceHeight):Math.min(targetWidth/sourceWidth,targetHeight/sourceHeight),width=sourceWidth*scale,height=sourceHeight*scale;return {x:(targetWidth-width)/2,y:(targetHeight-height)/2,width,height};}
                function options(){const width=Math.trunc(Number($('targetWidth').value)),height=Math.trunc(Number($('targetHeight').value)),quality=Math.min(1,Math.max(.5,Number($('quality').value)/100));if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width>MAX_SIDE||height>MAX_SIDE||width*height>MAX_OUTPUT_PIXELS)throw new Error('目标尺寸单边不能超过 12000 px，总像素不能超过 3000 万。');return {width,height,quality,type:$('format').value,mode:$('fitMode').value,background:$('background').value};}
                async function processImages(){if(!selectedFiles.length||processing)return;if(!window.JSZip){setStatus('本地 ZIP 组件未加载，请刷新页面后重试。','error');return;}let setting;try{setting=options();}catch(error){setStatus(error.message,'error');return;}processing=true;releaseResults();renderSummary();$('progress').hidden=false;$('progress').value=0;setStatus('正在处理图片…');const errors=[],used=new Set();let outputBytes=0;try{for(let index=0;index<selectedFiles.length;index++){const file=selectedFiles[index];try{const source=await decode(file);try{if(source.width>MAX_SIDE||source.height>MAX_SIDE||source.width*source.height>MAX_SOURCE_PIXELS)throw new Error('原图尺寸过大');const canvas=document.createElement('canvas');canvas.width=setting.width;canvas.height=setting.height;const context=canvas.getContext('2d');if(!context)throw new Error('浏览器无法创建画布');context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';if(setting.mode==='contain'||setting.type==='image/jpeg'){context.fillStyle=setting.background;context.fillRect(0,0,canvas.width,canvas.height);}const rect=targetRect(source.width,source.height,setting.width,setting.height,setting.mode);context.drawImage(source.image,rect.x,rect.y,rect.width,rect.height);const blob=await canvasBlob(canvas,setting.type,setting.quality);if(outputBytes+blob.size>MAX_OUTPUT_BYTES)throw new Error('输出总大小超过 250 MB，已停止处理');outputBytes+=blob.size;const name=outputName(file,setting.type,used);results.push({name,blob,url:URL.createObjectURL(blob),width:setting.width,height:setting.height});}finally{source.release();}}catch(error){errors.push(file.name+'：'+(error.message||'处理失败'));}$('progress').value=(index+1)/selectedFiles.length*100;renderResults(errors);setStatus('正在处理 '+(index+1)+' / '+selectedFiles.length+' 张图片…');await new Promise(resolve=>setTimeout(resolve,0));}renderResults(errors);$('download').disabled=!results.length;setStatus('处理完成：成功 '+results.length+' 张'+(errors.length?'，失败 '+errors.length+' 张。':'。'),errors.length?'warning':'success');}finally{processing=false;$('progress').hidden=true;$('progress').value=0;renderSummary();}}
                async function downloadZip(){if(!results.length||processing)return;if(!window.JSZip){setStatus('本地 ZIP 组件未加载，请刷新页面后重试。','error');return;}processing=true;$('download').disabled=true;$('process').disabled=true;$('clear').disabled=true;$('progress').hidden=false;setStatus('正在打包 ZIP…');try{const zip=new window.JSZip();results.forEach(result=>zip.file(result.name,result.blob));const blob=await zip.generateAsync({type:'blob',compression:'STORE'},meta=>{$('progress').value=meta.percent;setStatus('正在打包 ZIP：'+meta.percent.toFixed(0)+'%');});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='batch-resized-images.zip';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('ZIP 已生成并开始下载。','success');}catch(error){setStatus('ZIP 打包失败，可能是浏览器内存不足。','error');}finally{processing=false;$('progress').hidden=true;$('progress').value=0;renderSummary();$('download').disabled=!results.length;}}
                function clearAll(){if(processing)return;selectedFiles=[];$('files').value='';releaseResults();renderSummary();setStatus('请先选择图片。');}
                function invalidateOutput(){if(processing||!results.length)return;releaseResults();setStatus(selectedFiles.length?'参数已变更，请重新处理图片。':'请先选择图片。');}
                $('files').addEventListener('change',event=>resetFiles(event.target.files));['dragenter','dragover'].forEach(name=>$('dropZone').addEventListener(name,event=>{event.preventDefault();$('dropZone').classList.add('dragging');}));['dragleave','drop'].forEach(name=>$('dropZone').addEventListener(name,event=>{event.preventDefault();$('dropZone').classList.remove('dragging');}));$('dropZone').addEventListener('drop',event=>resetFiles(event.dataTransfer.files));['targetWidth','targetHeight','fitMode','background','suffix'].forEach(id=>$(id).addEventListener('input',invalidateOutput));$('quality').addEventListener('input',()=>{$('qualityValue').textContent=$('quality').value+'%';invalidateOutput();});$('format').addEventListener('change',()=>{$('qualityHint').textContent=$('format').value==='image/png'?'PNG 为无损格式，不使用质量参数。':'适用于 JPG / WebP';invalidateOutput();});$('process').addEventListener('click',processImages);$('download').addEventListener('click',downloadZip);$('clear').addEventListener('click',clearAll);window.addEventListener('beforeunload',releaseResults);
            })();
            </script>
<?php include '_footer.php'; ?>
