<?php
$title = '批量文件重命名打包';
$desc = '批量添加前后缀、查找替换和编号，预览无冲突后按新文件名打包下载 ZIP；文件只在浏览器中处理。';
include '_header.php';
?>
            <style>
            .rename-drop{display:flex;min-height:125px;align-items:center;justify-content:center;text-align:center;padding:20px;border:2px dashed #cbd5e1;border-radius:12px;background:rgba(248,250,252,.72);cursor:pointer}.rename-drop.dragging{border-color:#6366f1;background:rgba(99,102,241,.08)}.rename-drop strong{display:block;margin-bottom:7px;color:#334155}.rename-drop small{color:#64748b}.rename-settings{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px;margin-top:15px}.rename-settings label{display:block;margin-bottom:6px}.number-row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.number-toggle{display:flex!important;align-items:center;gap:7px;margin-top:10px!important}.preview-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:10px}.preview-wrap{overflow:auto;border:1px solid #dbe3ef;border-radius:10px}.rename-table{width:100%;border-collapse:collapse;min-width:620px}.rename-table th,.rename-table td{padding:10px 12px;border-bottom:1px solid #e2e8f0;text-align:left;overflow-wrap:anywhere}.rename-table th{position:sticky;top:0;background:#f8fafc;color:#475569;font-size:13px}.rename-table tr:last-child td{border-bottom:0}.rename-table .changed{color:#4f46e5;font-weight:600}.rename-table .error{color:#b91c1c}.empty-row{text-align:center!important;color:#64748b;padding:28px!important}.summary{display:flex;flex-wrap:wrap;gap:8px;margin-top:11px}.summary span{padding:5px 9px;border-radius:999px;background:#eef2ff;color:#4338ca;font-size:13px}.status-line{min-height:22px;margin-top:10px;color:#64748b}.status-line.error{color:#b91c1c}.status-line.success{color:#047857}
            html.theme-dark .rename-drop{background:rgba(30,41,59,.72);border-color:#475569}html.theme-dark .rename-drop strong{color:#e2e8f0}html.theme-dark .rename-table th{background:#1e293b}html.theme-dark .rename-table td,html.theme-dark .preview-wrap{border-color:#475569}html.theme-dark .summary span{background:#312e81;color:#c7d2fe}
            @media(max-width:900px){.rename-settings{grid-template-columns:1fr 1fr}}@media(max-width:560px){.rename-settings{grid-template-columns:1fr}.preview-head{align-items:flex-start;flex-direction:column}}
            </style>
            <div class="tool-panel">
                <label class="rename-drop" id="dropZone" for="files"><span><strong>点击或拖放多个文件</strong><small>最多 200 个，总大小不超过 250 MB；不会修改原文件</small></span></label>
                <input id="files" type="file" multiple hidden>
                <div class="rename-settings">
                    <div><label for="prefix">添加前缀</label><input id="prefix" maxlength="80" placeholder="例如：项目A_"></div><div><label for="suffix">添加后缀</label><input id="suffix" maxlength="80" placeholder="扩展名前添加"></div><div><label for="findText">查找文字</label><input id="findText" maxlength="80" placeholder="文件名中的文字"></div><div><label for="replaceText">替换为</label><input id="replaceText" maxlength="80" placeholder="留空表示删除"></div>
                    <div><label for="sortMode">文件顺序</label><select id="sortMode"><option value="selected">选择顺序</option><option value="name">按文件名排序</option></select></div><div><label for="numberStart">编号设置</label><div class="number-row"><input id="numberStart" type="number" min="0" max="999999" value="1" aria-label="编号起始值"><input id="numberDigits" type="number" min="1" max="6" value="3" aria-label="编号位数"></div></div><div><label class="number-toggle"><input id="addNumber" type="checkbox"> 在名称前添加编号</label></div><div><label class="number-toggle"><input id="caseSensitive" type="checkbox"> 查找时区分大小写</label></div>
                </div>
                <div class="btn-row"><button class="btn" id="downloadButton" type="button" disabled>按新名称打包 ZIP</button><button class="btn secondary" id="resetRules" type="button">清空规则</button><button class="btn secondary" id="clearFiles" type="button" disabled>移除全部文件</button></div>
                <div class="summary" id="summary"></div><p class="status-line" id="status" role="status">请先选择文件。</p>
            </div>
            <div class="tool-panel"><div class="preview-head"><strong>重命名预览</strong><small>扩展名默认保持不变</small></div><div class="preview-wrap"><table class="rename-table"><thead><tr><th>#</th><th>原文件名</th><th>新文件名</th><th>大小</th></tr></thead><tbody id="previewBody"><tr><td class="empty-row" colspan="4">选择文件后显示预览</td></tr></tbody></table></div></div>
            <script src="../static/vendor/jszip.min.js" onerror="this.onerror=null;this.src='https://unpkg.com/jszip@3.10.1/dist/jszip.min.js'"></script>
            <script>
            (()=>{
                'use strict';const MAX_FILES=200,MAX_TOTAL_BYTES=250*1024*1024,INVALID_NAME=/[<>:\"/\\|?*\u0000-\u001F]/g,RESERVED=/^(?:CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(?:\.|$)/i;const $=id=>document.getElementById(id);let selectedFiles=[],previewRows=[];
                function readable(bytes){return bytes>=1024*1024?(bytes/1024/1024).toFixed(2)+' MB':bytes>=1024?(bytes/1024).toFixed(1)+' KB':bytes+' B';}
                function splitName(name){const index=name.lastIndexOf('.');return index>0?{base:name.slice(0,index),ext:name.slice(index)}:{base:name,ext:''};}
                function safePart(value){return value.replace(INVALID_NAME,'_').replace(/[. ]+$/g,'').slice(0,120);}
                function replaceLiteral(value,find,replacement,caseSensitive){if(!find)return value;if(caseSensitive)return value.split(find).join(replacement);const escaped=find.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return value.replace(new RegExp(escaped,'gi'),replacement);}
                function orderedFiles(){return $('sortMode').value==='name'?[...selectedFiles].sort((a,b)=>a.name.localeCompare(b.name,'zh-CN',{numeric:true})):selectedFiles;}
                function buildPreview(){
                    const files=orderedFiles(),prefix=safePart($('prefix').value),suffix=safePart($('suffix').value),find=$('findText').value,replacement=$('replaceText').value,addNumber=$('addNumber').checked,start=Math.max(0,Math.min(999999,Number($('numberStart').value)||0)),digits=Math.max(1,Math.min(6,Number($('numberDigits').value)||1));previewRows=files.map((file,index)=>{const parts=splitName(file.name);let base=replaceLiteral(parts.base,find,replacement,$('caseSensitive').checked);base=safePart(base);const number=addNumber?String(start+index).padStart(digits,'0')+'_':'';let name=safePart(number+prefix+base+suffix)+parts.ext;if(!name||name===parts.ext)name='unnamed_'+String(index+1)+parts.ext;const invalid=RESERVED.test(name)||name.length>240;return {file,name,invalid,duplicate:false};});const counts=new Map();previewRows.forEach(row=>counts.set(row.name.toLocaleLowerCase(),(counts.get(row.name.toLocaleLowerCase())||0)+1));previewRows.forEach(row=>row.duplicate=counts.get(row.name.toLocaleLowerCase())>1);renderPreview();
                }
                function renderPreview(){const body=$('previewBody');body.replaceChildren();if(!previewRows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=4;td.className='empty-row';td.textContent='选择文件后显示预览';tr.appendChild(td);body.appendChild(tr);$('summary').replaceChildren();$('downloadButton').disabled=true;return;}let changed=0,errors=0;previewRows.forEach((row,index)=>{const tr=document.createElement('tr');[String(index+1),row.file.name,row.name+(row.duplicate?'（名称重复）':row.invalid?'（名称不可用）':''),readable(row.file.size)].forEach((text,column)=>{const td=document.createElement('td');td.textContent=text;if(column===2&&row.name!==row.file.name)td.className='changed';if(column===2&&(row.duplicate||row.invalid))td.className='error';tr.appendChild(td);});body.appendChild(tr);if(row.name!==row.file.name)changed++;if(row.duplicate||row.invalid)errors++;});$('summary').replaceChildren();[['文件',previewRows.length],['将改名',changed],['冲突',errors],['总大小',readable(previewRows.reduce((sum,row)=>sum+row.file.size,0))]].forEach(([label,value])=>{const span=document.createElement('span');span.textContent=label+'：'+value;$('summary').appendChild(span);});$('downloadButton').disabled=errors>0||!window.JSZip;$('status').textContent=errors?'发现名称冲突或不可用名称，请调整规则。':'预览无冲突，可以打包下载。';$('status').className='status-line '+(errors?'error':'success');}
                function loadFiles(fileList){const files=[...fileList],total=files.reduce((sum,file)=>sum+file.size,0);if(!files.length)return;if(files.length>MAX_FILES||total>MAX_TOTAL_BYTES){$('status').textContent='最多选择 200 个文件，总大小不能超过 250 MB。';$('status').className='status-line error';return;}selectedFiles=files;$('clearFiles').disabled=false;buildPreview();}
                async function downloadZip(){if(!previewRows.length||previewRows.some(row=>row.duplicate||row.invalid))return;if(!window.JSZip){$('status').textContent='ZIP 组件未加载，请刷新页面。';return;}const zip=new window.JSZip();previewRows.forEach(row=>zip.file(row.name,row.file,{binary:true}));$('downloadButton').disabled=true;$('status').textContent='正在生成 ZIP…';try{const blob=await zip.generateAsync({type:'blob',compression:'STORE'},metadata=>{$('status').textContent='正在生成 ZIP：'+metadata.percent.toFixed(0)+'%';});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='renamed-files.zip';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent='ZIP 已生成，原文件不会被修改。';$('status').className='status-line success';}catch(error){$('status').textContent='ZIP 生成失败，可能是文件过大或浏览器内存不足。';$('status').className='status-line error';}finally{$('downloadButton').disabled=false;}}
                $('files').addEventListener('change',event=>loadFiles(event.target.files));['dragenter','dragover'].forEach(name=>$('dropZone').addEventListener(name,event=>{event.preventDefault();$('dropZone').classList.add('dragging');}));['dragleave','drop'].forEach(name=>$('dropZone').addEventListener(name,event=>{event.preventDefault();$('dropZone').classList.remove('dragging');}));$('dropZone').addEventListener('drop',event=>loadFiles(event.dataTransfer.files));document.querySelectorAll('.rename-settings input,.rename-settings select').forEach(input=>input.addEventListener('input',buildPreview));$('downloadButton').addEventListener('click',downloadZip);$('resetRules').addEventListener('click',()=>{$('prefix').value='';$('suffix').value='';$('findText').value='';$('replaceText').value='';$('sortMode').value='selected';$('numberStart').value='1';$('numberDigits').value='3';$('addNumber').checked=false;$('caseSensitive').checked=false;buildPreview();});$('clearFiles').addEventListener('click',()=>{selectedFiles=[];previewRows=[];$('files').value='';$('clearFiles').disabled=true;$('status').textContent='请先选择文件。';$('status').className='status-line';renderPreview();});
            })();
            </script>
<?php include '_footer.php'; ?>
