<?php
$title = '批量图片加水印';
$desc = '一次为多张图片添加统一文字水印，并打包下载；图片只在浏览器中处理。';
include '_header.php';
?>
            <style>
            .watermark-drop{display:flex;min-height:128px;align-items:center;justify-content:center;padding:20px;border:2px dashed #cbd5e1;border-radius:12px;background:rgba(248,250,252,.7);text-align:center;cursor:pointer}.watermark-drop.dragging{border-color:#6366f1;background:rgba(99,102,241,.08)}.watermark-drop strong{display:block;margin-bottom:7px;color:#334155}.watermark-drop small{color:#64748b}.watermark-options{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:16px}.watermark-options label{display:block}.watermark-options input,.watermark-options select{width:100%;margin-top:7px}.watermark-options input[type=color]{height:40px;padding:2px}.watermark-options input[type=range]{padding:0}.watermark-summary{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.watermark-summary span{padding:5px 9px;border-radius:999px;background:#eef2ff;color:#4338ca;font-size:13px}.watermark-status{min-height:22px;margin:12px 0 0;color:#64748b}.watermark-status.error{color:#b91c1c}.watermark-status.success{color:#047857}.watermark-progress{width:100%;margin-top:10px}.watermark-actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:17px}.watermark-results{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.watermark-card{min-width:0;overflow:hidden;border:1px solid #dbe3ef;border-radius:11px;background:rgba(255,255,255,.72)}.watermark-card img{display:block;width:100%;height:132px;object-fit:contain;background:#f1f5f9}.watermark-card .body{padding:9px 10px}.watermark-card strong,.watermark-card small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.watermark-card strong{font-size:13px;color:#334155}.watermark-card small{margin-top:5px;color:#64748b;font-size:12px}.watermark-card.error{padding:12px;color:#b91c1c;font-size:13px}.watermark-empty{grid-column:1/-1;padding:32px;text-align:center;border:1px dashed #cbd5e1;border-radius:11px;color:#64748b}.privacy-note{margin:14px 0 0;color:#475569;font-size:13px}html.theme-dark .watermark-drop,html.theme-dark .watermark-card{background:rgba(30,41,59,.72);border-color:#475569}html.theme-dark .watermark-drop strong,html.theme-dark .watermark-card strong{color:#e2e8f0}html.theme-dark .watermark-card img{background:#0f172a}html.theme-dark .watermark-summary span{background:#312e81;color:#c7d2fe}@media(max-width:820px){.watermark-options{grid-template-columns:repeat(2,minmax(0,1fr))}.watermark-results{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:560px){.watermark-options,.watermark-results{grid-template-columns:1fr}.watermark-card img{height:175px}}
            </style>
            <div class="tool-panel">
                <label class="watermark-drop" id="dropZone" for="files"><span><strong>点击选择或拖放多张图片</strong><small>支持 JPG、PNG、WebP；最多 50 张，总大小不超过 200 MB</small></span></label>
                <input id="files" type="file" accept="image/jpeg,image/png,image/webp" multiple hidden>
                <div class="watermark-options">
                    <div><label for="text">水印文字</label><input id="text" maxlength="120" value="© 示例水印" placeholder="例如：仅供内部使用"></div>
                    <div><label for="position">水印位置</label><select id="position"><option value="bottom-right">右下角</option><option value="bottom-left">左下角</option><option value="top-right">右上角</option><option value="top-left">左上角</option><option value="center">正中间</option><option value="top-center">顶部居中</option><option value="bottom-center">底部居中</option><option value="center-left">左侧居中</option><option value="center-right">右侧居中</option></select></div>
                    <div><label for="fontSize">字号 <span id="fontSizeValue">4%</span></label><input id="fontSize" type="range" min="1" max="12" value="4"></div>
                    <div><label for="opacity">透明度 <span id="opacityValue">55%</span></label><input id="opacity" type="range" min="10" max="100" value="55"></div>
                    <div><label for="color">文字颜色</label><input id="color" type="color" value="#ffffff"></div>
                    <div><label for="format">导出格式</label><select id="format"><option value="image/jpeg">JPG</option><option value="image/webp" selected>WebP</option><option value="image/png">PNG</option></select></div>
                    <div><label for="quality">导出质量 <span id="qualityValue">88%</span></label><input id="quality" type="range" min="50" max="100" value="88"></div>
                    <div><label for="suffix">文件名后缀</label><input id="suffix" maxlength="40" value="_watermarked" placeholder="例如：_已加水印"></div>
                </div>
                <div class="watermark-summary" id="summary"></div><progress class="watermark-progress" id="progress" max="100" value="0" hidden></progress><p class="watermark-status" id="status" role="status">请先选择图片。</p>
                <div class="watermark-actions"><button class="btn" id="process" type="button" disabled>开始批量加水印</button><button class="btn success" id="download" type="button" disabled>打包下载 ZIP</button><button class="btn secondary" id="clear" type="button" disabled>移除全部图片</button></div>
                <p class="privacy-note">🔒 图片只在浏览器中处理，不会上传服务器。导出的新图片不保留 EXIF 信息（如拍摄位置）。</p>
            </div>
            <div class="tool-panel"><h3>处理结果</h3><div class="watermark-results" id="results"><div class="watermark-empty">处理完成后会在这里显示图片预览。</div></div></div>
            <script src="../static/vendor/jszip.min.js"></script>
            <script>
            (()=>{
                'use strict';
                const MAX_FILES=50,MAX_FILE_BYTES=40*1024*1024,MAX_TOTAL_BYTES=200*1024*1024,MAX_SOURCE_PIXELS=50000000,MAX_OUTPUT_BYTES=250*1024*1024,MAX_SIDE=16384;
                const allowedTypes=new Set(['image/jpeg','image/png','image/webp']),extensionByType={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};
                const $=id=>document.getElementById(id);let selectedFiles=[],results=[],processing=false;
                const readable=bytes=>bytes>=1048576?(bytes/1048576).toFixed(2)+' MB':bytes>=1024?(bytes/1024).toFixed(1)+' KB':bytes+' B';
                function setStatus(text,type=''){$('status').textContent=text;$('status').className='watermark-status '+type;}
                function releaseResults(){results.forEach(result=>URL.revokeObjectURL(result.url));results=[];renderResults();$('download').disabled=true;}
                function renderSummary(){const total=selectedFiles.reduce((sum,file)=>sum+file.size,0),box=$('summary');box.replaceChildren();if(selectedFiles.length){[['图片',selectedFiles.length],['原文件',readable(total)]].forEach(([label,value])=>{const item=document.createElement('span');item.textContent=label+'：'+value;box.appendChild(item);});}$('process').disabled=!selectedFiles.length||processing;$('clear').disabled=!selectedFiles.length||processing;}
                function renderResults(errors=[]){const box=$('results');box.replaceChildren();if(!results.length&&!errors.length){box.append(Object.assign(document.createElement('div'),{className:'watermark-empty',textContent:'处理完成后会在这里显示图片预览。'}));return;}results.forEach(result=>{const card=document.createElement('article'),image=new Image(),body=document.createElement('div'),name=document.createElement('strong'),meta=document.createElement('small');card.className='watermark-card';image.src=result.url;image.alt=result.name;image.loading='lazy';body.className='body';name.textContent=result.name;meta.textContent=result.width+' × '+result.height+' px · '+readable(result.blob.size);body.append(name,meta);card.append(image,body);box.appendChild(card);});errors.forEach(error=>{const card=document.createElement('div');card.className='watermark-card error';card.textContent=error;box.appendChild(card);});}
                function resetFiles(fileList){const incoming=[...fileList];if(!incoming.length)return;const invalid=incoming.find(file=>!allowedTypes.has(file.type)||file.size>MAX_FILE_BYTES),total=incoming.reduce((sum,file)=>sum+file.size,0);if(incoming.length>MAX_FILES||total>MAX_TOTAL_BYTES){setStatus('最多选择 50 张图片，总大小不能超过 200 MB。','error');return;}if(invalid){setStatus('仅支持单张不超过 40 MB 的 JPG、PNG、WebP 图片。','error');return;}selectedFiles=incoming;releaseResults();renderSummary();setStatus('已选择 '+incoming.length+' 张图片，可以开始加水印。','success');}
                function outputName(file,type,used){const raw=file.name.replace(/\.[^.]+$/,''),base=raw.replace(/[<>:"/\\|?*\u0000-\u001f]/g,'_').replace(/[. ]+$/g,'').trim().slice(0,110)||'image',suffix=$('suffix').value.replace(/[<>:"/\\|?*\u0000-\u001f]/g,'_').slice(0,40),ext=extensionByType[type];let name=base+suffix+'.'+ext,index=2;while(used.has(name.toLocaleLowerCase())){name=base+suffix+'_'+index+'.'+ext;index++;}used.add(name.toLocaleLowerCase());return name;}
                async function decode(file){if('createImageBitmap'in window){try{const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});return {image:bitmap,width:bitmap.width,height:bitmap.height,release:()=>bitmap.close()};}catch(error){}}const url=URL.createObjectURL(file);try{const image=await new Promise((resolve,reject)=>{const item=new Image();item.onload=()=>resolve(item);item.onerror=()=>reject(new Error('无法读取图片'));item.src=url;});return {image,width:image.naturalWidth,height:image.naturalHeight,release:()=>URL.revokeObjectURL(url)};}catch(error){URL.revokeObjectURL(url);throw error;}}
                const canvasBlob=(canvas,type,quality)=>new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('浏览器无法生成此格式的图片')),type,type==='image/png'?undefined:quality));
                function settings(){const text=$('text').value.trim(),size=Number($('fontSize').value),opacity=Number($('opacity').value)/100,quality=Number($('quality').value)/100;if(!text)throw new Error('请输入水印文字。');return {text,size,opacity,quality,type:$('format').value,color:$('color').value,position:$('position').value};}
                function drawWatermark(context,width,height,setting){const padding=Math.max(12,Math.round(Math.min(width,height)*.028));let fontSize=Math.max(12,Math.round(Math.min(width,height)*setting.size/100));context.font='600 '+fontSize+'px sans-serif';const maxWidth=Math.max(1,width-padding*2),measured=context.measureText(setting.text).width;if(measured>maxWidth){fontSize=Math.max(9,Math.floor(fontSize*maxWidth/measured));context.font='600 '+fontSize+'px sans-serif';}const positions={'top-left':[padding,padding,'left','top'],'top-center':[width/2,padding,'center','top'],'top-right':[width-padding,padding,'right','top'],'center-left':[padding,height/2,'left','middle'],'center':[width/2,height/2,'center','middle'],'center-right':[width-padding,height/2,'right','middle'],'bottom-left':[padding,height-padding,'left','bottom'],'bottom-center':[width/2,height-padding,'center','bottom'],'bottom-right':[width-padding,height-padding,'right','bottom']},point=positions[setting.position]||positions['bottom-right'];context.save();context.globalAlpha=setting.opacity;context.fillStyle=setting.color;context.textAlign=point[2];context.textBaseline=point[3];context.shadowColor='rgba(0,0,0,.5)';context.shadowBlur=Math.max(1,Math.round(fontSize/9));context.fillText(setting.text,point[0],point[1],maxWidth);context.restore();}
                async function processImages(){if(!selectedFiles.length||processing)return;if(!window.JSZip){setStatus('本地 ZIP 组件未加载，请刷新页面后重试。','error');return;}let setting;try{setting=settings();}catch(error){setStatus(error.message,'error');return;}processing=true;releaseResults();renderSummary();$('progress').hidden=false;$('progress').value=0;setStatus('正在处理图片…');const errors=[],used=new Set();let outputBytes=0;try{for(let index=0;index<selectedFiles.length;index++){const file=selectedFiles[index];try{const source=await decode(file);try{if(source.width>MAX_SIDE||source.height>MAX_SIDE||source.width*source.height>MAX_SOURCE_PIXELS)throw new Error('原图尺寸过大');const canvas=document.createElement('canvas');canvas.width=source.width;canvas.height=source.height;const context=canvas.getContext('2d');if(!context)throw new Error('浏览器无法创建画布');context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';if(setting.type==='image/jpeg'){context.fillStyle='#ffffff';context.fillRect(0,0,canvas.width,canvas.height);}context.drawImage(source.image,0,0);drawWatermark(context,canvas.width,canvas.height,setting);const blob=await canvasBlob(canvas,setting.type,setting.quality);if(outputBytes+blob.size>MAX_OUTPUT_BYTES)throw new Error('输出总大小超过 250 MB，已停止处理');outputBytes+=blob.size;const name=outputName(file,setting.type,used);results.push({name,blob,url:URL.createObjectURL(blob),width:canvas.width,height:canvas.height});}finally{source.release();}}catch(error){errors.push(file.name+'：'+(error.message||'处理失败'));}$('progress').value=(index+1)/selectedFiles.length*100;renderResults(errors);setStatus('正在处理 '+(index+1)+' / '+selectedFiles.length+' 张图片…');await new Promise(resolve=>setTimeout(resolve,0));}renderResults(errors);$('download').disabled=!results.length;setStatus('处理完成：成功 '+results.length+' 张'+(errors.length?'，失败 '+errors.length+' 张。':'。'),errors.length?'warning':'success');}finally{processing=false;$('progress').hidden=true;$('progress').value=0;renderSummary();}}
                async function downloadZip(){if(!results.length||processing)return;if(!window.JSZip){setStatus('本地 ZIP 组件未加载，请刷新页面后重试。','error');return;}processing=true;$('download').disabled=true;$('process').disabled=true;$('clear').disabled=true;$('progress').hidden=false;setStatus('正在打包 ZIP…');try{const zip=new window.JSZip();results.forEach(result=>zip.file(result.name,result.blob));const blob=await zip.generateAsync({type:'blob',compression:'STORE'},meta=>{$('progress').value=meta.percent;setStatus('正在打包 ZIP：'+meta.percent.toFixed(0)+'%');});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='batch-watermarked-images.zip';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('ZIP 已生成并开始下载。','success');}catch(error){setStatus('ZIP 打包失败，可能是浏览器内存不足。','error');}finally{processing=false;$('progress').hidden=true;$('progress').value=0;renderSummary();$('download').disabled=!results.length;}}
                function clearAll(){if(processing)return;selectedFiles=[];$('files').value='';releaseResults();renderSummary();setStatus('请先选择图片。');}
                function invalidateOutput(){if(processing||!results.length)return;releaseResults();setStatus(selectedFiles.length?'参数已变更，请重新处理图片。':'请先选择图片。');}
                $('files').addEventListener('change',event=>resetFiles(event.target.files));['dragenter','dragover'].forEach(name=>$('dropZone').addEventListener(name,event=>{event.preventDefault();$('dropZone').classList.add('dragging');}));['dragleave','drop'].forEach(name=>$('dropZone').addEventListener(name,event=>{event.preventDefault();$('dropZone').classList.remove('dragging');}));$('dropZone').addEventListener('drop',event=>resetFiles(event.dataTransfer.files));['text','position','color','suffix'].forEach(id=>$(id).addEventListener('input',invalidateOutput));['fontSize','opacity','quality'].forEach(id=>$(id).addEventListener('input',()=>{$(id+'Value').textContent=$(id).value+'%';invalidateOutput();}));$('format').addEventListener('change',invalidateOutput);$('process').addEventListener('click',processImages);$('download').addEventListener('click',downloadZip);$('clear').addEventListener('click',clearAll);window.addEventListener('beforeunload',releaseResults);
            })();
            </script>
<?php include '_footer.php'; ?>
