<?php
$title = '证件照与工牌生成';
$desc = '裁切常用证件照，并按竖版或横版生成带姓名、工号的工牌图片。照片只在浏览器中处理。';
include '_header.php';
?>
<style>
.idphoto-grid{display:grid;grid-template-columns:330px minmax(0,1fr);gap:18px}.idphoto-drop{display:flex;min-height:145px;align-items:center;justify-content:center;text-align:center;border:2px dashed #cbd5e1;border-radius:12px;background:#f8fafc;cursor:pointer;padding:18px}.idphoto-drop.dragging{border-color:#6366f1;background:#eef2ff}.idphoto-drop strong{display:block;margin-bottom:7px}.idphoto-drop small,.idphoto-status{color:#64748b;font-size:12px}.idphoto-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:14px}.idphoto-options label{display:block}.idphoto-options input,.idphoto-options select{width:100%;margin-top:6px}.idphoto-card-toggle{grid-column:1/-1}.idphoto-card-toggle input{width:auto;margin:0 6px 0 0}.idphoto-card-fields{grid-column:1/-1;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.idphoto-card-fields .wide{grid-column:1/-1}.idphoto-range{display:grid;grid-template-columns:88px 1fr 42px;gap:8px;align-items:center;margin-top:11px}.idphoto-range input{margin:0}.idphoto-actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:16px}.idphoto-status{min-height:22px;margin:12px 0 0}.idphoto-status.error{color:#b91c1c}.idphoto-status.success{color:#047857}.idphoto-preview{display:grid;place-items:center;min-height:390px;padding:18px;border:1px dashed #cbd5e1;border-radius:12px;background:#f8fafc}.idphoto-preview canvas{max-width:100%;max-height:560px;box-shadow:0 8px 20px rgba(15,23,42,.15)}.idphoto-empty{color:#64748b;text-align:center}.idphoto-results{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:16px}.idphoto-results img{display:block;max-width:100%;max-height:310px;margin:auto;border:1px solid #dbe3ef;border-radius:10px;background:#fff}.idphoto-results h3{margin:0 0 9px}.idphoto-results p{margin:8px 0;color:#64748b;font-size:12px}.idphoto-note{margin:14px 0 0;padding:11px 13px;border:1px solid #fde68a;border-radius:9px;background:#fffbeb;color:#92400e;font-size:13px}html.theme-dark .idphoto-drop,.idphoto-preview{background:#0f172a;border-color:#475569}@media(max-width:800px){.idphoto-grid{grid-template-columns:1fr}.idphoto-preview{min-height:280px}}@media(max-width:460px){.idphoto-options,.idphoto-results,.idphoto-card-fields{grid-template-columns:1fr}.idphoto-card-fields .wide{grid-column:auto}.idphoto-range{grid-template-columns:76px 1fr 38px}}
</style>
<div class="tool-panel"><div class="idphoto-grid"><div>
<label class="idphoto-drop" id="dropZone" for="photoFile"><span><strong>点击选择或拖放正面照片</strong><small>支持 JPG、PNG、WebP；单张不超过 40 MB</small></span></label><input id="photoFile" type="file" accept="image/jpeg,image/png,image/webp" hidden>
<div class="idphoto-options">
<div><label for="preset">证件照规格</label><select id="preset"><option value="one">一寸（25 × 35 mm）</option><option value="smallOne">小一寸（22 × 32 mm）</option><option value="two">二寸（35 × 49 mm）</option><option value="smallTwo">小二寸（35 × 45 mm）</option><option value="largeOne">大一寸 / 护照（33 × 48 mm）</option><option value="largeTwo">大二寸（35 × 53 mm）</option><option value="social">社保回执照（26 × 32 mm）</option><option value="graduate">毕业生图像采集（41 × 55 mm）</option><option value="custom">自定义尺寸</option></select></div>
<div><label for="background">照片底色</label><select id="background"><option value="#ffffff">白色</option><option value="#438edb" selected>蓝色</option><option value="#e53935">红色</option><option value="#d9dde3">浅灰色</option></select></div>
<div id="customWidthWrap" hidden><label for="customWidth">宽度（mm）</label><input id="customWidth" type="number" min="10" max="80" value="25"></div><div id="customHeightWrap" hidden><label for="customHeight">高度（mm）</label><input id="customHeight" type="number" min="10" max="100" value="35"></div>
<label class="idphoto-card-toggle"><input id="makeCard" type="checkbox" checked>同时生成工牌（可选）</label>
<div class="idphoto-card-fields" id="cardFields"><div><label for="cardLayout">工牌版式</label><select id="cardLayout"><option value="portrait">竖版（54 × 86 mm）</option><option value="landscape">横版（86 × 54 mm）</option><option value="custom">自定义大小</option></select></div><div><label for="cardColor">工牌颜色</label><select id="cardColor"><option value="#0878b8">商务蓝</option><option value="#1f7a4c">绿色</option><option value="#7c3aed">紫色</option><option value="#dc2626">红色</option></select></div><div id="cardWidthWrap" hidden><label for="cardWidth">工牌宽度（mm）</label><input id="cardWidth" type="number" min="30" max="200" value="54"></div><div id="cardHeightWrap" hidden><label for="cardHeight">工牌高度（mm）</label><input id="cardHeight" type="number" min="30" max="200" value="86"></div><div><label for="photoName">姓名（可选）</label><input id="photoName" type="text" maxlength="20" placeholder="例如：张三"></div><div><label for="employeeNo">工号（可选）</label><input id="employeeNo" type="text" maxlength="30" placeholder="例如：A2026001"></div><div><label for="department">部门（可选）</label><input id="department" type="text" maxlength="30" placeholder="例如：产品部"></div><div><label for="jobTitle">职务（可选）</label><input id="jobTitle" type="text" maxlength="30" placeholder="例如：产品经理"></div><div class="wide"><label for="cardTitle">工牌标题（可选）</label><input id="cardTitle" type="text" maxlength="20" value="工作证"></div></div>
</div>
<div class="idphoto-range"><span>缩放</span><input id="scale" type="range" min="100" max="250" value="100"><output id="scaleOut">100%</output></div><div class="idphoto-range"><span>左右位置</span><input id="offsetX" type="range" min="-100" max="100" value="0"><output id="offsetXOut">0</output></div><div class="idphoto-range"><span>上下位置</span><input id="offsetY" type="range" min="-100" max="100" value="0"><output id="offsetYOut">0</output></div><div class="idphoto-range"><span>亮度</span><input id="brightness" type="range" min="50" max="150" value="100"><output id="brightnessOut">100%</output></div><div class="idphoto-range"><span>对比度</span><input id="contrast" type="range" min="50" max="150" value="100"><output id="contrastOut">100%</output></div><div class="idphoto-range"><span>饱和度</span><input id="saturation" type="range" min="0" max="200" value="100"><output id="saturationOut">100%</output></div>
<div class="idphoto-actions"><button class="btn" id="resetPosition" type="button" disabled>重置位置</button><button class="btn success" id="downloadPhoto" type="button" disabled>下载证件照 JPG</button><button class="btn" id="downloadCard" type="button" disabled>下载工牌 JPG</button></div><p class="idphoto-status" id="status" role="status">请先选择照片。</p>
</div><div class="idphoto-preview" id="preview"><div class="idphoto-empty">上传照片后，可用缩放和位置控制把头像放在合适的位置。</div></div></div><p class="idphoto-note">提示：此工具用于尺寸裁切和工牌排版，不做自动人像抠图或官方证件合规审核。请使用背景干净、正面清晰的照片，并以办理机构的最新要求为准。</p></div>
<div class="tool-panel" id="resultPanel" hidden><div class="idphoto-results"><div><h3>单张证件照</h3><img id="photoResult" alt="生成的证件照预览"><p id="photoInfo"></p></div><div id="cardResultWrap"><h3>工牌成品</h3><img id="cardResult" alt="生成的工牌预览"><p id="cardInfo"></p></div></div></div>
<script>
(()=>{'use strict';
const MAX_FILE_BYTES=40*1024*1024,MAX_SOURCE_PIXELS=50000000,MAX_OUTPUT_PIXELS=30000000,DPI=300,allowedTypes=new Set(['image/jpeg','image/png','image/webp']),presets={one:[25,35],smallOne:[22,32],two:[35,49],smallTwo:[35,45],largeOne:[33,48],largeTwo:[35,53],social:[26,32],graduate:[41,55]},$=id=>document.getElementById(id),px=mm=>Math.round(mm/25.4*DPI),readable=bytes=>(bytes/1024).toFixed(1)+' KB';let source=null,photoBlob=null,cardBlob=null,photoUrl='',cardUrl='';
function status(text,type=''){$('status').textContent=text;$('status').className='idphoto-status '+type}function revoke(url){if(url)URL.revokeObjectURL(url)}function release(){revoke(photoUrl);revoke(cardUrl);photoUrl='';cardUrl='';photoBlob=null;cardBlob=null;$('downloadPhoto').disabled=true;$('downloadCard').disabled=true;$('resultPanel').hidden=true}
function outputSize(){let size=presets[$('preset').value];if(!size)size=[Number($('customWidth').value),Number($('customHeight').value)];const [w,h]=size.map(Number);if(!Number.isFinite(w)||!Number.isFinite(h)||w<10||w>80||h<10||h>100)throw new Error('自定义尺寸请填写宽 10–80 mm、高 10–100 mm。');const width=px(w),height=px(h);if(width*height>MAX_OUTPUT_PIXELS)throw new Error('输出尺寸过大。');return {mmWidth:w,mmHeight:h,width,height}}
async function decode(file){if('createImageBitmap'in window){const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});return {image:bitmap,width:bitmap.width,height:bitmap.height,close:()=>bitmap.close()}}const url=URL.createObjectURL(file);try{const image=await new Promise((resolve,reject)=>{const item=new Image();item.onload=()=>resolve(item);item.onerror=()=>reject(new Error('无法读取图片'));item.src=url});return {image,width:image.naturalWidth,height:image.naturalHeight,close:()=>URL.revokeObjectURL(url)}}catch(error){URL.revokeObjectURL(url);throw error}}
const toBlob=canvas=>new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('浏览器无法生成图片')),'image/jpeg',.92));
function drawCover(ctx,x,y,width,height){const scale=Number($('scale').value)/100,ratio=Math.max(width/source.width,height/source.height)*scale,drawW=source.width*ratio,drawH=source.height*ratio;ctx.save();ctx.filter='brightness('+$('brightness').value+'%) contrast('+$('contrast').value+'%) saturate('+$('saturation').value+'%)';ctx.drawImage(source.image,x+(width-drawW)/2+Number($('offsetX').value)/100*width,y+(height-drawH)/2+Number($('offsetY').value)/100*height,drawW,drawH);ctx.restore()}
function drawPhoto(canvas,ctx,size){ctx.fillStyle=$('background').value;ctx.fillRect(0,0,size.width,size.height);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';drawCover(ctx,0,0,size.width,size.height)}
function cardSize(){const layout=$('cardLayout').value;if(layout==='portrait')return {width:px(54),height:px(86),name:'竖版 54 × 86 mm'};if(layout==='landscape')return {width:px(86),height:px(54),name:'横版 86 × 54 mm'};const mmWidth=Number($('cardWidth').value),mmHeight=Number($('cardHeight').value);if(!Number.isFinite(mmWidth)||!Number.isFinite(mmHeight)||mmWidth<30||mmWidth>200||mmHeight<30||mmHeight>200)throw new Error('自定义工牌请填写宽、高各 30–200 mm。');return {width:px(mmWidth),height:px(mmHeight),name:'自定义 '+mmWidth+' × '+mmHeight+' mm'}}
function drawCard(canvas,ctx,card){const portrait=card.height>=card.width,color=$('cardColor').value;ctx.fillStyle=color;ctx.fillRect(0,0,card.width,card.height);ctx.fillStyle='rgba(255,255,255,.09)';ctx.beginPath();ctx.arc(card.width*(portrait?.1:.95),card.height*(portrait?.82:.1),card.width*.5,0,Math.PI*2);ctx.fill();const title=$('cardTitle').value.trim()||'工作证',name=$('photoName').value.trim()||'未填写',number=$('employeeNo').value.trim(),department=$('department').value.trim(),job=$('jobTitle').value.trim(),photo=portrait?{x:card.width*.22,y:card.height*.23,w:card.width*.56,h:card.height*.31}:{x:card.width*.08,y:card.height*.22,w:card.width*.31,h:card.height*.57};ctx.fillStyle='#fff';ctx.fillRect(photo.x-px(1),photo.y-px(1),photo.w+px(2),photo.h+px(2));ctx.save();ctx.beginPath();ctx.rect(photo.x,photo.y,photo.w,photo.h);ctx.clip();drawCover(ctx,photo.x,photo.y,photo.w,photo.h);ctx.restore();ctx.fillStyle='#fff';ctx.textAlign=portrait?'center':'left';ctx.font='700 '+Math.round(card.width*(portrait?.09:.055))+'px sans-serif';ctx.fillText(title,portrait?card.width/2:card.width*.48,portrait?card.height*.14:card.height*.22);const textX=portrait?card.width/2:card.width*.48,textY=portrait?card.height*.62:card.height*.43;ctx.font='600 '+Math.round(card.width*(portrait?.055:.045))+'px sans-serif';ctx.fillText(name,textX,textY);ctx.font='400 '+Math.round(card.width*(portrait?.031:.026))+'px sans-serif';const rows=[department?'部门：'+department:'',job?'职务：'+job:'',number?'工号：'+number:''];rows.filter(Boolean).forEach((row,index)=>ctx.fillText(row,textX,textY+card.height*(portrait?.075:.12)*(index+1)));const lineY=textY+card.height*(portrait?.075:.12)*(Math.max(1,rows.filter(Boolean).length)+.55);ctx.strokeStyle='rgba(255,255,255,.55)';ctx.lineWidth=Math.max(1,card.width*.004);ctx.beginPath();ctx.moveTo(portrait?card.width*.20:card.width*.48,lineY);ctx.lineTo(portrait?card.width*.80:card.width*.91,lineY);ctx.stroke()}
async function render(){if(!source)return;let size;try{size=outputSize()}catch(error){status(error.message,'error');return}release();try{const photoCanvas=document.createElement('canvas');photoCanvas.width=size.width;photoCanvas.height=size.height;drawPhoto(photoCanvas,photoCanvas.getContext('2d'),size);photoBlob=await toBlob(photoCanvas);photoUrl=URL.createObjectURL(photoBlob);$('photoResult').src=photoUrl;$('photoInfo').textContent=size.mmWidth+' × '+size.mmHeight+' mm · '+size.width+' × '+size.height+' px · '+readable(photoBlob.size);$('downloadPhoto').disabled=false;const cardEnabled=$('makeCard').checked;$('cardResultWrap').hidden=!cardEnabled;if(cardEnabled){const card=cardSize();if(card.width*card.height>MAX_OUTPUT_PIXELS)throw new Error('工牌尺寸过大。');const cardCanvas=document.createElement('canvas');cardCanvas.width=card.width;cardCanvas.height=card.height;drawCard(cardCanvas,cardCanvas.getContext('2d'),card);cardBlob=await toBlob(cardCanvas);cardUrl=URL.createObjectURL(cardBlob);$('cardResult').src=cardUrl;$('cardInfo').textContent=card.name+' · '+card.width+' × '+card.height+' px · '+readable(cardBlob.size);$('downloadCard').disabled=false}const preview=document.createElement('canvas'),ratio=Math.min(1,280/size.width,540/size.height);preview.width=Math.max(1,Math.round(size.width*ratio));preview.height=Math.max(1,Math.round(size.height*ratio));drawPhoto(preview,preview.getContext('2d'),{width:preview.width,height:preview.height});$('preview').replaceChildren(preview);$('resultPanel').hidden=false;status(cardEnabled?'已生成证件照和工牌。':'已生成证件照。','success')}catch(error){status(error.message||'生成失败。','error')}}
function loadFile(file){if(!file)return;if(!allowedTypes.has(file.type)||file.size>MAX_FILE_BYTES){status('请选择不超过 40 MB 的 JPG、PNG 或 WebP 图片。','error');return}release();if(source)source.close();status('正在读取照片…');decode(file).then(result=>{if(result.width*result.height>MAX_SOURCE_PIXELS||result.width>16384||result.height>16384){result.close();throw new Error('原图尺寸过大，最多 5000 万像素且单边不超过 16384 px。')}source=result;$('resetPosition').disabled=false;render()}).catch(error=>status(error.message||'照片读取失败。','error'))}
function download(blob,name){if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}function updateRange(id,out){$(out).textContent=id==='scale'?$(id).value+'%':$(id).value;render()}
$('photoFile').addEventListener('change',event=>loadFile(event.target.files[0]));['dragenter','dragover'].forEach(type=>$('dropZone').addEventListener(type,event=>{event.preventDefault();$('dropZone').classList.add('dragging')}));['dragleave','drop'].forEach(type=>$('dropZone').addEventListener(type,event=>{event.preventDefault();$('dropZone').classList.remove('dragging')}));$('dropZone').addEventListener('drop',event=>loadFile(event.dataTransfer.files[0]));$('preset').addEventListener('change',()=>{const custom=$('preset').value==='custom';$('customWidthWrap').hidden=!custom;$('customHeightWrap').hidden=!custom;render()});$('makeCard').addEventListener('change',()=>{$('cardFields').hidden=!$('makeCard').checked;render()});$('cardLayout').addEventListener('change',()=>{const custom=$('cardLayout').value==='custom';$('cardWidthWrap').hidden=!custom;$('cardHeightWrap').hidden=!custom;render()});['background','customWidth','customHeight','cardColor','cardWidth','cardHeight','photoName','employeeNo','department','jobTitle','cardTitle'].forEach(id=>$(id).addEventListener('input',render));[['scale','scaleOut'],['offsetX','offsetXOut'],['offsetY','offsetYOut'],['brightness','brightnessOut'],['contrast','contrastOut'],['saturation','saturationOut']].forEach(([id,out])=>$(id).addEventListener('input',()=>updateRange(id,out)));$('resetPosition').addEventListener('click',()=>{['scale','offsetX','offsetY'].forEach(id=>$(id).value=id==='scale'?100:0);$('scaleOut').textContent='100%';$('offsetXOut').textContent='0';$('offsetYOut').textContent='0';render()});$('downloadPhoto').addEventListener('click',()=>download(photoBlob,'证件照.jpg'));$('downloadCard').addEventListener('click',()=>download(cardBlob,'工作证.jpg'));window.addEventListener('beforeunload',()=>{release();if(source)source.close()})})();
</script>
<?php include '_footer.php'; ?>
