<?php
$title = '报价单生成';
$desc = '本地制作可打印的报价单，自动计算折扣、税额和总计。';
include '_header.php';
?>
            <div class="quote-layout">
                <section class="tool-panel">
                    <div class="quote-fields">
                        <label>报价单编号<input id="quoteNo" type="text" maxlength="60"></label><label>报价日期<input id="quoteDate" type="date"></label>
                        <label>报价方<input id="seller" type="text" maxlength="120" placeholder="公司或个人名称"></label><label>联系信息<input id="sellerContact" type="text" maxlength="200" placeholder="电话、邮箱或地址"></label>
                        <label>客户名称<input id="buyer" type="text" maxlength="120"></label><label>币种<select id="currency"><option value="CNY">人民币（¥）</option><option value="USD">美元（$）</option><option value="EUR">欧元（€）</option></select></label>
                    </div>
                    <div class="quote-items-head"><h3>报价项目</h3><button class="btn small" id="addItem" type="button">+ 添加项目</button></div>
                    <div class="quote-items" id="items"></div>
                    <div class="quote-options"><label>折扣（%）<input id="discount" type="number" min="0" max="100" step="0.01" value="0"></label><label>税率（%）<input id="taxRate" type="number" min="0" max="100" step="0.01" value="0"></label></div>
                    <label for="notes">备注（可选）</label><textarea id="notes" maxlength="1500" placeholder="例如：报价有效期、付款方式、交付周期等。"></textarea>
                    <div class="btn-row"><button class="btn success" id="print" type="button">打印 / 保存 PDF</button><button class="btn" id="save" type="button">保存草稿</button><button class="btn secondary" id="clear" type="button">清空</button></div>
                    <p class="quote-status" id="status" role="status" aria-live="polite">报价数据仅保存在当前浏览器。报价单不是正式发票，请确认金额、税率及适用规则。</p>
                </section>
                <section class="tool-panel quote-preview-wrap"><div class="quote-paper" id="preview"></div></section>
            </div>
            <style>
            .quote-layout{display:grid;grid-template-columns:minmax(340px,1fr) minmax(360px,1fr);gap:18px}.quote-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.quote-fields label,.quote-options label{display:flex;flex-direction:column}.quote-fields input,.quote-fields select,.quote-options input{width:100%;margin-top:5px}.quote-items-head{display:flex;align-items:center;justify-content:space-between;margin:18px 0 8px}.quote-items-head h3{margin:0}.quote-items{display:grid;gap:8px}.quote-item{display:grid;grid-template-columns:minmax(0,1fr) 90px 78px 104px auto;gap:7px;align-items:center}.quote-item input{margin:0;width:100%}.quote-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin:14px 0}.quote-layout textarea{width:100%;min-height:100px;margin-top:5px}.quote-status{min-height:20px;color:#64748b;font-size:12px}.quote-status.success{color:#047857}.quote-status.error{color:#b91c1c}.quote-preview-wrap{overflow:auto;background:#e2e8f0}.quote-paper{width:min(100%,760px);min-height:930px;margin:auto;padding:48px;background:#fff;color:#0f172a;box-shadow:0 6px 22px rgba(15,23,42,.12);font:14px/1.55 Arial,sans-serif}.quote-paper h1{margin:0;color:#1d4ed8;font-size:30px;letter-spacing:2px}.quote-paper .meta{display:grid;grid-template-columns:1fr auto;gap:18px;margin:24px 0}.quote-paper .muted{color:#64748b}.quote-paper table{width:100%;border-collapse:collapse;margin:22px 0}.quote-paper th,.quote-paper td{padding:9px 8px;border-bottom:1px solid #cbd5e1;text-align:left;vertical-align:top}.quote-paper th{background:#eff6ff;color:#1e3a8a}.quote-paper .number{text-align:right}.quote-paper .totals{margin-left:auto;width:min(100%,290px)}.quote-paper .totals div{display:flex;justify-content:space-between;padding:5px 0}.quote-paper .totals strong{font-size:18px;color:#1d4ed8}.quote-paper .notes{margin-top:28px;padding-top:14px;border-top:1px solid #cbd5e1;white-space:pre-wrap}.quote-paper .footer{margin-top:56px;color:#64748b;font-size:12px}@media(max-width:900px){.quote-layout{grid-template-columns:1fr}.quote-paper{min-height:720px}}@media(max-width:600px){.quote-fields,.quote-options{grid-template-columns:1fr}.quote-item{grid-template-columns:minmax(0,1fr) 1fr 38px}.quote-item .item-price{grid-column:1/3}}html.theme-dark .quote-preview-wrap{background:#0f172a}
            </style>
            <script>
            (()=>{
                'use strict';
                const STORAGE_KEY='office_quote_generator_draft_v1',MAX_ITEMS=50,$=id=>document.getElementById(id),fieldIds=['quoteNo','quoteDate','seller','sellerContact','buyer','currency','discount','taxRate','notes'];
                const state=()=>({fields:Object.fromEntries(fieldIds.map(id=>[id,$(id).value])),items:[...$('items').querySelectorAll('.quote-item')].map(row=>({name:row.querySelector('.item-name').value,spec:row.querySelector('.item-spec').value,qty:row.querySelector('.item-qty').value,price:row.querySelector('.item-price').value}))});
                const amount=value=>Math.max(0,Math.min(1e12,Number(value)||0)),esc=value=>String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
                function status(message,type=''){const node=$('status');node.textContent=message;node.className='quote-status '+type;}
                function currencyFormatter(){return new Intl.NumberFormat('zh-CN',{style:'currency',currency:$('currency').value,minimumFractionDigits:2,maximumFractionDigits:2});}
                function itemRow(item={}){const row=document.createElement('div');row.className='quote-item';row.innerHTML='<input class="item-name" maxlength="160" placeholder="项目名称"><input class="item-spec" maxlength="100" placeholder="规格"><input class="item-qty" type="number" min="0" max="1000000" step="0.01" placeholder="数量"><input class="item-price" type="number" min="0" max="1000000000" step="0.01" placeholder="单价"><button class="btn secondary small" type="button" aria-label="删除项目">×</button>';row.querySelector('.item-name').value=item.name||'';row.querySelector('.item-spec').value=item.spec||'';row.querySelector('.item-qty').value=item.qty||'';row.querySelector('.item-price').value=item.price||'';row.querySelector('button').addEventListener('click',()=>{row.remove();if(!$('items').children.length)itemRow();render();});$('items').appendChild(row);}
                function totals(){const items=state().items,subtotal=items.reduce((sum,item)=>sum+amount(item.qty)*amount(item.price),0),discount=Math.min(100,amount($('discount').value)),taxRate=Math.min(100,amount($('taxRate').value)),discountValue=subtotal*discount/100,taxable=subtotal-discountValue,tax=taxable*taxRate/100;return {items,subtotal,discount,discountValue,taxRate,tax,total:taxable+tax};}
                function render(){const data=state(),summary=totals(),format=currencyFormatter(),tableRows=summary.items.filter(item=>item.name||item.spec||item.qty||item.price).map(item=>'<tr><td>'+esc(item.name||'未命名项目')+'</td><td>'+esc(item.spec)+'</td><td class="number">'+esc(item.qty||'0')+'</td><td class="number">'+format.format(amount(item.price))+'</td><td class="number">'+format.format(amount(item.qty)*amount(item.price))+'</td></tr>').join('')||'<tr><td colspan="5" class="muted">暂无报价项目</td></tr>';const seller=esc(data.fields.seller||'未填写报价方'),buyer=esc(data.fields.buyer||'未填写客户');$('preview').innerHTML='<h1>报价单</h1><div class="meta"><div><strong>'+seller+'</strong><br><span class="muted">'+esc(data.fields.sellerContact)+'</span></div><div>报价单编号：'+esc(data.fields.quoteNo||'未填写')+'<br>报价日期：'+esc(data.fields.quoteDate||'未填写')+'<br>客户：'+buyer+'</div></div><table><thead><tr><th>项目</th><th>规格</th><th class="number">数量</th><th class="number">单价</th><th class="number">金额</th></tr></thead><tbody>'+tableRows+'</tbody></table><div class="totals"><div><span>小计</span><span>'+format.format(summary.subtotal)+'</span></div><div><span>折扣（'+summary.discount+'%）</span><span>-'+format.format(summary.discountValue)+'</span></div><div><span>税额（'+summary.taxRate+'%）</span><span>'+format.format(summary.tax)+'</span></div><div><strong>合计</strong><strong>'+format.format(summary.total)+'</strong></div></div><div class="notes"><strong>备注</strong><br>'+esc(data.fields.notes||'无').replace(/\n/g,'<br>')+'</div><div class="footer">本报价单由办公工具站在本地生成，请确认金额、税率和报价有效期。</div>';try{localStorage.setItem(STORAGE_KEY,JSON.stringify(data));}catch{}}
                function restore(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved){Object.entries(saved.fields||{}).forEach(([id,value])=>{if($(id))$(id).value=value||'';});(saved.items||[]).slice(0,MAX_ITEMS).forEach(itemRow);status('已恢复本机草稿。','success');}}catch{}if(!$('items').children.length)itemRow();if(!$('quoteDate').value)$('quoteDate').value=new Date().toISOString().slice(0,10);if(!$('quoteNo').value)$('quoteNo').value='Q-'+$('quoteDate').value.replaceAll('-','')+'-001';render();}
                function printQuote(){render();const content=$('preview').innerHTML,windowRef=window.open('','_blank');if(!windowRef){status('浏览器拦截了打印窗口，请允许弹出窗口后重试。','error');return;}windowRef.opener=null;windowRef.document.write('<!doctype html><html><head><meta charset="utf-8"><title>报价单</title><style>body{margin:0;background:#fff;color:#0f172a;font:14px/1.55 Arial,sans-serif}.quote{width:760px;min-height:930px;margin:auto;padding:48px;box-sizing:border-box}h1{margin:0;color:#1d4ed8;font-size:30px;letter-spacing:2px}.meta{display:grid;grid-template-columns:1fr auto;gap:18px;margin:24px 0}.muted,.footer{color:#64748b}table{width:100%;border-collapse:collapse;margin:22px 0}th,td{padding:9px 8px;border-bottom:1px solid #cbd5e1;text-align:left;vertical-align:top}th{background:#eff6ff;color:#1e3a8a}.number{text-align:right}.totals{margin-left:auto;width:290px}.totals div{display:flex;justify-content:space-between;padding:5px 0}.totals strong{font-size:18px;color:#1d4ed8}.notes{margin-top:28px;padding-top:14px;border-top:1px solid #cbd5e1;white-space:pre-wrap}.footer{margin-top:56px;font-size:12px}@page{size:A4;margin:0}</style></head><body><main class="quote">'+content+'</main><script>window.onload=()=>window.print()<\/script></body></html>');windowRef.document.close();status('已打开打印页面，可选择“另存为 PDF”。','success');}
                $('addItem').addEventListener('click',()=>{if($('items').children.length>=MAX_ITEMS){status('最多可添加 '+MAX_ITEMS+' 个项目。','error');return;}itemRow();render();});$('items').addEventListener('input',render);fieldIds.forEach(id=>$(id).addEventListener('input',render));$('print').addEventListener('click',printQuote);$('save').addEventListener('click',()=>{render();status('草稿已保存到当前浏览器。','success');});$('clear').addEventListener('click',()=>{fieldIds.forEach(id=>$(id).value='');$('items').replaceChildren();try{localStorage.removeItem(STORAGE_KEY);}catch{};restore();status('已清空草稿。','success');});restore();
            })();
            </script>
<?php include '_footer.php'; ?>
