<?php
$title = '在线屏幕测试';
$desc = '全屏色卡循环测试，辅助检查屏幕坏点、亮点与色彩显示。';
include '_header.php';
?>
            <div class="screen-info tool-panel"><h2>在线屏幕测试</h2><ol><li>点击“开始测试”进入全屏色卡模式。</li><li>使用左右方向键或点击屏幕切换测试颜色。</li><li>按 <kbd>Esc</kbd> 退出全屏，也可点击“结束测试”。</li></ol><div class="screen-notice"><b>注意：</b>本工具仅提供基础色卡辅助观察，不能替代专业检测或维修。</div><button class="btn success" id="start-test" type="button">开始测试</button></div>
            <div class="screen-stage" id="screen-stage" hidden tabindex="0" aria-label="屏幕色卡测试区域"><div class="screen-stage-top"><span id="screen-label">红色</span><span id="screen-count">1 / 15</span></div><div class="screen-stage-help">← → 切换颜色 · 点击屏幕也可切换 · Esc 退出</div><button id="end-test" type="button">结束测试</button></div>
            <style>
            .screen-info{max-width:760px;margin:auto}.screen-info h2{margin-bottom:14px}.screen-info ol{padding-left:22px;line-height:2;color:#475569}.screen-notice{margin:18px 0;padding:14px;border:1px solid #fed7aa;border-radius:9px;color:#c2410c;background:#fff7ed;line-height:1.7}.screen-stage{position:fixed;inset:0;z-index:9999;background:#f00;color:#fff;cursor:pointer;outline:0}.screen-stage-top{position:absolute;top:22px;left:24px;right:24px;display:flex;justify-content:space-between;font-size:14px;text-shadow:0 1px 3px rgba(0,0,0,.45)}.screen-stage-help{position:absolute;bottom:24px;left:50%;transform:translateX(-50%);padding:8px 12px;border-radius:20px;background:rgba(0,0,0,.24);font-size:13px;white-space:nowrap}.screen-stage button{position:absolute;top:52px;right:24px;padding:8px 12px;border:1px solid rgba(255,255,255,.6);border-radius:8px;color:#fff;background:rgba(0,0,0,.18);cursor:pointer}@media(max-width:600px){.screen-stage-top{top:16px;left:16px;right:16px}.screen-stage button{top:45px;right:16px}.screen-stage-help{bottom:16px;font-size:11px}}
            </style>
            <script>
            (function(){const colors=[['红色','#ef4444'],['绿色','#22c55e'],['蓝色','#3b82f6'],['白色','#ffffff'],['黑色','#000000'],['灰色','#808080'],['黄色','#facc15'],['青色','#06b6d4'],['紫色','#8b5cf6'],['橙色','#f97316'],['粉色','#ec4899'],['深蓝','#1e3a8a'],['浅灰','#e5e7eb'],['暖白','#fff7ed'],['纯黑','#111827']];const stage=document.getElementById('screen-stage'),label=document.getElementById('screen-label'),count=document.getElementById('screen-count');let index=0;function paint(){const color=colors[index];stage.style.background=color[1];stage.style.color=['#ffffff','#e5e7eb','#000000','#111827'].includes(color[1])?'#111827':'#fff';label.textContent=color[0];count.textContent=(index+1)+' / '+colors.length}function stop(){stage.hidden=true;if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});}function start(){stage.hidden=false;paint();stage.focus();stage.requestFullscreen&&stage.requestFullscreen().catch(()=>{});}document.getElementById('start-test').addEventListener('click',start);document.getElementById('end-test').addEventListener('click',event=>{event.stopPropagation();stop()});stage.addEventListener('click',()=>{index=(index+1)%colors.length;paint()});document.addEventListener('keydown',event=>{if(stage.hidden)return;if(event.key==='Escape')stop();if(event.key==='ArrowRight'||event.key==='ArrowDown'){event.preventDefault();index=(index+1)%colors.length;paint()}if(event.key==='ArrowLeft'||event.key==='ArrowUp'){event.preventDefault();index=(index-1+colors.length)%colors.length;paint()}});document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&!stage.hidden)stage.hidden=true});})();
            </script>
<?php include '_footer.php'; ?>
