<?php
$title = '文本隐私脱敏';
$desc = '在浏览器本地识别并遮盖邮箱、手机号、中国身份证、银行卡和 IPv4 地址，支持自定义敏感词；文本不会上传服务器。';
include '_header.php';
?>
            <style>
            .redactor-options{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin:12px 0}.check-card{display:flex;align-items:center;gap:8px;padding:10px;border:1px solid #dbe3ef;border-radius:9px;background:rgba(248,250,252,.7);cursor:pointer}.editor-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.editor-grid textarea{width:100%;min-height:330px;resize:vertical;line-height:1.65}.editor-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:7px}.editor-head small{color:#64748b}.custom-row{display:grid;grid-template-columns:minmax(0,1fr) 190px;gap:10px}.summary{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px;min-height:32px}.summary span{padding:5px 9px;border-radius:999px;background:#eef2ff;color:#4338ca;font-size:13px}.warning{margin-top:12px;padding:11px;border-radius:9px;background:#fff7ed;color:#9a3412;font-size:13px;line-height:1.6}.status-line{min-height:22px;margin-top:10px;color:#64748b}.status-line.error{color:#b91c1c}
            html.theme-dark .check-card{background:rgba(30,41,59,.7);border-color:#475569}html.theme-dark .summary span{background:#312e81;color:#c7d2fe}html.theme-dark .warning{background:#431407;color:#fed7aa}
            @media(max-width:780px){.redactor-options{grid-template-columns:1fr 1fr}.editor-grid{grid-template-columns:1fr}.custom-row{grid-template-columns:1fr}}
            </style>
            <div class="tool-panel">
                <div class="custom-row"><div><label for="customTerms">自定义敏感词（每行一个，最多 100 个）</label><textarea id="customTerms" rows="3" placeholder="例如：客户姓名&#10;公司内部项目名"></textarea></div><div><label for="mode">脱敏方式</label><select id="mode"><option value="token">类型标记（推荐）</option><option value="partial">保留部分信息</option></select></div></div>
                <div class="redactor-options">
                    <label class="check-card"><input type="checkbox" data-type="email" checked> 邮箱</label><label class="check-card"><input type="checkbox" data-type="phone" checked> 中国大陆手机号</label><label class="check-card"><input type="checkbox" data-type="idcard" checked> 中国身份证</label><label class="check-card"><input type="checkbox" data-type="bankcard" checked> 银行卡号</label><label class="check-card"><input type="checkbox" data-type="ipv4" checked> IPv4 地址</label><label class="check-card"><input type="checkbox" data-type="custom" checked> 自定义词</label>
                </div>
                <div class="btn-row"><button class="btn" id="redactButton" type="button">开始脱敏</button><button class="btn secondary" id="exampleButton" type="button">填入示例</button><button class="btn secondary" id="clearButton" type="button">清空</button><button class="btn success" id="copyButton" type="button" disabled>复制结果</button><button class="btn success" id="downloadButton" type="button" disabled>下载 TXT</button></div>
                <p class="warning">规则匹配可能存在漏报或误报，无法可靠识别人名、普通地址及上下文含义。正式对外发布前请人工复核。</p>
            </div>
            <div class="tool-panel">
                <div class="editor-grid"><div><div class="editor-head"><label for="sourceText">原始文本</label><small id="sourceCount">0 字符</small></div><textarea id="sourceText" maxlength="2000000" placeholder="粘贴需要脱敏的文本，最多 200 万字符"></textarea></div><div><div class="editor-head"><label for="resultText">脱敏结果</label><small id="resultCount">0 字符</small></div><textarea id="resultText" readonly placeholder="处理结果将在这里显示"></textarea></div></div>
                <div class="summary" id="summary"></div><p class="status-line" id="status" role="status">所有处理均在浏览器本地完成。</p>
            </div>
            <script>
            (()=>{
                'use strict';const MAX_TEXT_LENGTH=2000000,MAX_CUSTOM_TERMS=100;const $=id=>document.getElementById(id);const labels={email:'邮箱',phone:'手机号',idcard:'身份证',bankcard:'银行卡',ipv4:'IPv4',custom:'自定义词'};
                function luhnValid(value){const digits=value.replace(/[ -]/g,'');if(!/^\d{13,19}$/.test(digits)||/^(\d)\1+$/.test(digits))return false;let sum=0,double=false;for(let i=digits.length-1;i>=0;i--){let digit=Number(digits[i]);if(double){digit*=2;if(digit>9)digit-=9;}sum+=digit;double=!double;}return sum%10===0;}
                function idCardValid(value){if(!/^\d{17}[\dXx]$/.test(value))return false;const weights=[7,9,10,5,8,4,2,1,6,3,7,9,10,5,8,4,2],checks='10X98765432';let sum=0;for(let i=0;i<17;i++)sum+=Number(value[i])*weights[i];return checks[sum%11]===value[17].toUpperCase();}
                function ipv4Valid(value){return value.split('.').every(part=>String(Number(part))===part&&Number(part)<=255);}
                function replacement(type,value,mode){if(mode==='token')return '['+labels[type]+']';if(type==='email'){const parts=value.split('@');return parts[0].slice(0,1)+'***@'+parts[1];}if(type==='phone')return value.slice(0,3)+'****'+value.slice(-4);if(type==='idcard')return value.slice(0,6)+'********'+value.slice(-4);if(type==='bankcard'){const digits=value.replace(/\D/g,'');return '**** **** **** '+digits.slice(-4);}if(type==='ipv4')return value.split('.').map((part,index)=>index<2?part:'*').join('.');return value.length<=2?'**':value[0]+'*'.repeat(Math.min(value.length-2,8))+value.at(-1);}
                function collectMatches(text,enabled){const matches=[];const add=(type,regex,validator=()=>true)=>{if(!enabled.has(type))return;for(const match of text.matchAll(regex)){if(validator(match[0]))matches.push({type,start:match.index,end:match.index+match[0].length,value:match[0]});}};add('email',/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,63}/gi);add('idcard',/(?<!\d)\d{17}[\dXx](?!\w)/g,idCardValid);add('phone',/(?<!\d)(?:\+?86[- ]?)?1[3-9]\d{9}(?!\d)/g);add('bankcard',/(?<!\d)(?:\d[ -]?){13,19}(?!\d)/g,luhnValid);add('ipv4',/(?<![\d.])(?:\d{1,3}\.){3}\d{1,3}(?![\d.])/g,ipv4Valid);if(enabled.has('custom')){const terms=[...new Set($('customTerms').value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean))].slice(0,MAX_CUSTOM_TERMS).sort((a,b)=>b.length-a.length);for(const term of terms){let start=0;while((start=text.indexOf(term,start))!==-1){matches.push({type:'custom',start,end:start+term.length,value:term});start+=term.length;}}}return matches;}
                function redact(){const text=$('sourceText').value;if(text.length>MAX_TEXT_LENGTH){$('status').textContent='文本超过 200 万字符，请分段处理。';$('status').className='status-line error';return;}const enabled=new Set([...document.querySelectorAll('[data-type]:checked')].map(input=>input.dataset.type)),matches=collectMatches(text,enabled).sort((a,b)=>a.start-b.start||(b.end-b.start)-(a.end-a.start));const selected=[];let cursor=-1;for(const match of matches){if(match.start>=cursor){selected.push(match);cursor=match.end;}}let output='',position=0;const counts={};for(const match of selected){output+=text.slice(position,match.start)+replacement(match.type,match.value,$('mode').value);position=match.end;counts[match.type]=(counts[match.type]||0)+1;}output+=text.slice(position);$('resultText').value=output;$('resultCount').textContent=output.length+' 字符';$('summary').replaceChildren();Object.entries(counts).forEach(([type,count])=>{const badge=document.createElement('span');badge.textContent=labels[type]+' '+count+' 处';$('summary').appendChild(badge);});$('copyButton').disabled=!output;$('downloadButton').disabled=!output;$('status').textContent=selected.length?'已处理 '+selected.length+' 处，请人工复核结果。':'未发现所选类型的敏感信息。';$('status').className='status-line';}
                async function copyResult(){try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText($('resultText').value);else{$('resultText').select();document.execCommand('copy');}$('status').textContent='结果已复制。';}catch(error){$('status').textContent='复制失败，请手动复制。';}}
                $('sourceText').addEventListener('input',event=>$('sourceCount').textContent=event.target.value.length+' 字符');$('redactButton').addEventListener('click',redact);$('exampleButton').addEventListener('click',()=>{$('sourceText').value='联系人邮箱：demo@example.com，手机：13800138000，身份证：11010519491231002X，银行卡：4111 1111 1111 1111，服务器：192.168.1.20，项目代号：北斗计划。';$('customTerms').value='北斗计划';$('sourceText').dispatchEvent(new Event('input'));redact();});$('clearButton').addEventListener('click',()=>{$('sourceText').value='';$('resultText').value='';$('customTerms').value='';$('summary').replaceChildren();$('copyButton').disabled=true;$('downloadButton').disabled=true;$('sourceCount').textContent='0 字符';$('resultCount').textContent='0 字符';$('status').textContent='所有处理均在浏览器本地完成。';});$('copyButton').addEventListener('click',copyResult);$('downloadButton').addEventListener('click',()=>{const blob=new Blob([$('resultText').value],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='redacted-text.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
            })();
            </script>
<?php include '_footer.php'; ?>
