<?php
$title = 'ZIP 压缩包工具';
$desc = '把文件或文件夹打包为 ZIP，也可以查看压缩包并提取选定文件；文件只在浏览器中处理。';
include '_header.php';
?>
            <style>
            .zip-tabs{display:flex;gap:8px;margin-bottom:16px}.zip-tab{border:1px solid #cbd5e1;background:#fff;color:#334155}.zip-tab.active{border-color:#6366f1;background:#6366f1;color:#fff}.zip-view[hidden]{display:none}.zip-drop{display:flex;min-height:120px;align-items:center;justify-content:center;text-align:center;padding:20px;border:2px dashed #cbd5e1;border-radius:12px;background:rgba(248,250,252,.72)}.zip-drop.dragging{border-color:#6366f1;background:rgba(99,102,241,.08)}.zip-drop strong{display:block;margin-bottom:7px}.zip-drop small{color:#64748b}.zip-actions{display:flex;flex-wrap:wrap;gap:9px;justify-content:center;margin-top:12px}.zip-options{display:grid;grid-template-columns:2fr 1fr;gap:12px;margin-top:15px}.zip-options input,.zip-options select{width:100%;margin-top:6px}.zip-summary{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.zip-summary span{padding:5px 9px;border-radius:999px;background:#eef2ff;color:#4338ca;font-size:13px}.zip-status{min-height:22px;margin:11px 0 0;color:#64748b}.zip-status.error{color:#b91c1c}.zip-status.success{color:#047857}.zip-progress{width:100%;margin-top:10px}.zip-table-wrap{overflow:auto;margin-top:14px;border:1px solid #dbe3ef;border-radius:10px}.zip-table{width:100%;min-width:650px;border-collapse:collapse}.zip-table th,.zip-table td{padding:9px 11px;border-bottom:1px solid #e2e8f0;text-align:left;overflow-wrap:anywhere}.zip-table th{background:#f8fafc;color:#475569;font-size:13px}.zip-table tr:last-child td{border-bottom:0}.zip-table .bad{color:#b91c1c}.zip-toolbar{display:flex;flex-wrap:wrap;align-items:end;gap:10px;margin-top:14px}.zip-toolbar label{flex:1;min-width:180px}.zip-toolbar input{width:100%;margin-top:6px}.privacy-note{margin:14px 0 0;color:#475569;font-size:13px}html.theme-dark .zip-tab{background:#1e293b;border-color:#475569;color:#e2e8f0}html.theme-dark .zip-tab.active{background:#6366f1}html.theme-dark .zip-drop{background:rgba(30,41,59,.72);border-color:#475569}html.theme-dark .zip-table th{background:#1e293b}html.theme-dark .zip-table td,html.theme-dark .zip-table-wrap{border-color:#475569}html.theme-dark .zip-summary span{background:#312e81;color:#c7d2fe}@media(max-width:650px){.zip-options{grid-template-columns:1fr}.zip-tabs>*{flex:1}.zip-toolbar{align-items:stretch;flex-direction:column}.zip-toolbar>*{width:100%}}
            </style>
            <div class="zip-tabs" role="tablist" aria-label="ZIP 功能">
                <button class="btn zip-tab active" type="button" role="tab" aria-selected="true" aria-controls="createView" data-view="createView">创建 ZIP</button>
                <button class="btn zip-tab" type="button" role="tab" aria-selected="false" aria-controls="extractView" data-view="extractView">查看与提取</button>
            </div>
            <section class="tool-panel zip-view" id="createView" role="tabpanel">
                <div class="zip-drop" id="createDrop"><div><strong>选择文件或拖放到这里</strong><small>最多 500 个文件，总大小不超过 250 MB</small><div class="zip-actions"><button class="btn" id="chooseFiles" type="button">选择文件</button><button class="btn secondary" id="chooseFolder" type="button">选择文件夹</button></div></div></div>
                <input id="fileInput" type="file" multiple hidden><input id="folderInput" type="file" webkitdirectory multiple hidden>
                <div class="zip-options"><div><label for="archiveName">压缩包名称</label><input id="archiveName" value="我的文件" maxlength="80"></div><div><label for="compressionLevel">压缩强度</label><select id="compressionLevel"><option value="1">快速</option><option value="6" selected>均衡</option><option value="9">更小</option></select></div></div>
                <div class="zip-summary" id="createSummary"></div><progress class="zip-progress" id="createProgress" max="100" value="0" hidden></progress><p class="zip-status" id="createStatus" role="status">请先选择文件。</p>
                <div class="btn-row"><button class="btn" id="createZip" type="button" disabled>生成并下载 ZIP</button><button class="btn secondary" id="clearCreate" type="button" disabled>移除全部文件</button></div>
            </section>
            <section class="tool-panel zip-view" id="extractView" role="tabpanel" hidden>
                <label class="zip-drop" id="extractDrop" for="zipInput"><span><strong>点击或拖放 ZIP 压缩包</strong><small>文件不超过 250 MB；会先检查数量、展开大小和压缩比</small></span></label><input id="zipInput" type="file" accept=".zip,application/zip" hidden>
                <div class="zip-summary" id="extractSummary"></div><p class="zip-status" id="extractStatus" role="status">请先选择 ZIP 文件。</p>
                <div id="extractResults" hidden><div class="zip-toolbar"><label for="entrySearch">筛选文件<input id="entrySearch" type="search" placeholder="输入文件名"></label><button class="btn secondary" id="selectAll" type="button">选择全部可见</button><button class="btn secondary" id="clearSelection" type="button">取消选择</button></div><div class="zip-table-wrap"><table class="zip-table"><thead><tr><th><span class="sr-only">选择</span></th><th>压缩包内路径</th><th>原始大小</th><th>压缩后</th><th>状态</th></tr></thead><tbody id="entryBody"></tbody></table></div><progress class="zip-progress" id="extractProgress" max="100" value="0" hidden></progress><div class="btn-row"><button class="btn" id="extractSelected" type="button" disabled>提取所选文件</button></div></div>
                <p class="privacy-note">🔒 文件只在浏览器中处理，不会上传到服务器。加密 ZIP 暂不支持。</p>
            </section>
            <script src="../static/vendor/jszip.min.js" onerror="this.onerror=null;this.src='https://unpkg.com/jszip@3.10.1/dist/jszip.min.js'"></script>
            <script>
            (()=>{
                'use strict';
                const MAX_FILES=500,MAX_INPUT_BYTES=250*1024*1024,MAX_EXPANDED_BYTES=500*1024*1024,MAX_RATIO=200;
                const $=id=>document.getElementById(id);let sourceFiles=[],loadedZip=null,entries=[];
                const readable=bytes=>bytes>=1073741824?(bytes/1073741824).toFixed(2)+' GB':bytes>=1048576?(bytes/1048576).toFixed(2)+' MB':bytes>=1024?(bytes/1024).toFixed(1)+' KB':bytes+' B';
                function safeArchivePath(value){const path=value.replaceAll('\\','/').replace(/^\/+/,''),parts=path.split('/').filter(Boolean);if(!parts.length||parts.some(part=>part==='.'||part==='..'||/[\u0000-\u001f]/.test(part)))return null;return parts.join('/').slice(0,500);}
                function safeDownloadName(value,fallback){const name=value.replace(/[<>:"/\\|?*\u0000-\u001f]/g,'_').replace(/[. ]+$/g,'').trim().slice(0,80);return name||fallback;}
                function setStatus(id,text,type=''){$(id).textContent=text;$(id).className='zip-status '+type;}
                function download(blob,name){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
                function summary(id,items){const box=$(id);box.replaceChildren();items.forEach(([label,value])=>{const span=document.createElement('span');span.textContent=label+'：'+value;box.appendChild(span);});}
                function loadCreateFiles(fileList){const incoming=[...fileList],combined=[...sourceFiles];for(const file of incoming){const raw=file.webkitRelativePath||file.name,path=safeArchivePath(raw);if(path&&!combined.some(item=>item.path.toLocaleLowerCase()===path.toLocaleLowerCase()))combined.push({file,path});}const total=combined.reduce((sum,item)=>sum+item.file.size,0);if(combined.length>MAX_FILES||total>MAX_INPUT_BYTES){setStatus('createStatus','最多 500 个文件，总大小不能超过 250 MB。','error');return;}sourceFiles=combined;summary('createSummary',[['文件',sourceFiles.length],['总大小',readable(total)]]);$('createZip').disabled=!sourceFiles.length;$('clearCreate').disabled=!sourceFiles.length;setStatus('createStatus',sourceFiles.length?'已准备好，可以生成 ZIP。':'请先选择文件。',sourceFiles.length?'success':'');}
                async function createZip(){if(!sourceFiles.length||!window.JSZip)return;const zip=new window.JSZip(),level=Number($('compressionLevel').value);sourceFiles.forEach(item=>zip.file(item.path,item.file,{binary:true}));$('createZip').disabled=true;$('createProgress').hidden=false;setStatus('createStatus','正在压缩，请稍候…');try{const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level},platform:'DOS'},meta=>{$('createProgress').value=meta.percent;setStatus('createStatus','正在压缩：'+meta.percent.toFixed(0)+'%');});download(blob,safeDownloadName($('archiveName').value,'我的文件')+'.zip');setStatus('createStatus','ZIP 已生成并开始下载。','success');}catch(e){setStatus('createStatus','生成失败，文件可能过大或浏览器内存不足。','error');}finally{$('createZip').disabled=false;$('createProgress').hidden=true;$('createProgress').value=0;}}
                function renderEntries(){const query=$('entrySearch').value.trim().toLocaleLowerCase(),body=$('entryBody');body.replaceChildren();entries.forEach((entry,index)=>{if(query&&!entry.name.toLocaleLowerCase().includes(query))return;const tr=document.createElement('tr'),check=document.createElement('input');check.type='checkbox';check.dataset.index=String(index);check.disabled=!entry.safe;check.addEventListener('change',updateExtractButton);const cells=[null,entry.name,readable(entry.uncompressed),readable(entry.compressed),entry.safe?'可提取':entry.reason];cells.forEach((value,column)=>{const td=document.createElement('td');if(column===0)td.appendChild(check);else td.textContent=value;if(column===4&&!entry.safe)td.className='bad';tr.appendChild(td);});body.appendChild(tr);});updateExtractButton();}
                function updateExtractButton(){$('extractSelected').disabled=!document.querySelector('#entryBody input:checked');}
                async function loadArchive(file){if(!file)return;if(file.size>MAX_INPUT_BYTES){setStatus('extractStatus','ZIP 文件不能超过 250 MB。','error');return;}if(!window.JSZip){setStatus('extractStatus','ZIP 组件未加载，请刷新页面。','error');return;}setStatus('extractStatus','正在读取压缩包…');$('extractResults').hidden=true;try{loadedZip=await window.JSZip.loadAsync(file,{createFolders:true});const files=Object.values(loadedZip.files).filter(item=>!item.dir);if(files.length>1000)throw new Error('压缩包超过 1000 个文件，已停止处理。');let expanded=0,compressed=0;entries=files.map(item=>{const original=item.unsafeOriginalName||item.name,name=safeArchivePath(item.name),u=Number(item._data&&item._data.uncompressedSize)||0,c=Number(item._data&&item._data.compressedSize)||0,ratio=u/Math.max(c,1);expanded+=u;compressed+=c;let reason='';if(!name||original!==item.name)reason='路径不安全';else if(u>MAX_INPUT_BYTES)reason='单个文件超过 250 MB';else if(u>10485760&&ratio>MAX_RATIO)reason='压缩比异常';return {item,name:name||item.name,uncompressed:u,compressed:c,safe:!reason,reason};});if(expanded>MAX_EXPANDED_BYTES)throw new Error('解压后预计超过 500 MB，已停止处理。');summary('extractSummary',[['文件',entries.length],['压缩后',readable(compressed)],['预计展开',readable(expanded)]]);$('extractResults').hidden=false;renderEntries();setStatus('extractStatus','读取完成，请选择需要提取的文件。','success');}catch(error){loadedZip=null;entries=[];setStatus('extractStatus',error.message&&error.message.includes('已停止')?error.message:'无法读取该 ZIP，文件可能损坏、加密或格式不受支持。','error');}}
                async function extractSelected(){const indexes=[...document.querySelectorAll('#entryBody input:checked')].map(input=>Number(input.dataset.index)),selected=indexes.map(index=>entries[index]).filter(entry=>entry&&entry.safe);if(!selected.length)return;$('extractSelected').disabled=true;$('extractProgress').hidden=false;try{if(selected.length===1){const blob=await selected[0].item.async('blob',meta=>$('extractProgress').value=meta.percent);download(blob,selected[0].name.split('/').pop());}else{const output=new window.JSZip();for(let i=0;i<selected.length;i++){const entry=selected[i],blob=await entry.item.async('blob');output.file(entry.name,blob);$('extractProgress').value=(i+1)/selected.length*70;}const blob=await output.generateAsync({type:'blob',compression:'STORE'},meta=>$('extractProgress').value=70+meta.percent*.3);download(blob,'提取的文件.zip');}setStatus('extractStatus','所选文件已提取并开始下载。','success');}catch(e){setStatus('extractStatus','提取失败，压缩包可能损坏或浏览器内存不足。','error');}finally{$('extractProgress').hidden=true;$('extractProgress').value=0;updateExtractButton();}}
                document.querySelectorAll('.zip-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.zip-tab').forEach(item=>{const active=item===tab;item.classList.toggle('active',active);item.setAttribute('aria-selected',String(active));$(item.dataset.view).hidden=!active;});}));
                $('chooseFiles').addEventListener('click',()=>$('fileInput').click());$('chooseFolder').addEventListener('click',()=>$('folderInput').click());$('fileInput').addEventListener('change',e=>loadCreateFiles(e.target.files));$('folderInput').addEventListener('change',e=>loadCreateFiles(e.target.files));
                ['dragenter','dragover'].forEach(type=>$('createDrop').addEventListener(type,e=>{e.preventDefault();$('createDrop').classList.add('dragging');}));['dragleave','drop'].forEach(type=>$('createDrop').addEventListener(type,e=>{e.preventDefault();$('createDrop').classList.remove('dragging');}));$('createDrop').addEventListener('drop',e=>loadCreateFiles(e.dataTransfer.files));$('createZip').addEventListener('click',createZip);$('clearCreate').addEventListener('click',()=>{sourceFiles=[];$('fileInput').value='';$('folderInput').value='';summary('createSummary',[]);$('createZip').disabled=true;$('clearCreate').disabled=true;setStatus('createStatus','请先选择文件。');});
                $('zipInput').addEventListener('change',e=>loadArchive(e.target.files[0]));['dragenter','dragover'].forEach(type=>$('extractDrop').addEventListener(type,e=>{e.preventDefault();$('extractDrop').classList.add('dragging');}));['dragleave','drop'].forEach(type=>$('extractDrop').addEventListener(type,e=>{e.preventDefault();$('extractDrop').classList.remove('dragging');}));$('extractDrop').addEventListener('drop',e=>loadArchive([...e.dataTransfer.files].find(file=>/\.zip$/i.test(file.name))||e.dataTransfer.files[0]));$('entrySearch').addEventListener('input',renderEntries);$('selectAll').addEventListener('click',()=>{document.querySelectorAll('#entryBody input:not(:disabled)').forEach(input=>input.checked=true);updateExtractButton();});$('clearSelection').addEventListener('click',()=>{document.querySelectorAll('#entryBody input').forEach(input=>input.checked=false);updateExtractButton();});$('extractSelected').addEventListener('click',extractSelected);
            })();
            </script>
<?php include '_footer.php'; ?>
